language: python

services: docker

python:
  - "3.6"

install: pip install tox

script:
  - tox

after_success:
  # Report coverage to codecov
  - pip install codecov
  - codecov

deploy:

    # Deploy latest and version to Dockerhub
  - provider: script
    script: deploy/docker.sh
    on:
      branch: master

    # Deploy to PyPI
  - provider: script
    script: deploy/pypi.sh
    on:
      branch: master
