# Automatically generated by Honest Code
# Do not edit this file as it will be overwritten

Feature: Attacks API
  As an API user
  I want to use the Attacks API

  Scenario: Get attacks is HAL compliance
    Given there are 2 attacks available
    When the user makes a "GET" request to "/attacks/" endpoint
    Then the response is HAL
    And the api responds with 2 attacks
