# Automatically generated by Honest Code
# Do not edit this file as it will be overwritten

Feature: Historic executions
  As an user
  I want to keep historical data for executed attacks

  Scenario: Running all executors for a plan mark the plan as executed
    Given the two_executors module is available in planners
    And the attack1 module is available in attacks
    And a plan exists in the database
    And 1 executors for attack1 exists in the database related to the plan
    When the scheduler executes it
    Then the executor is marked as executed in the database
    And the plan is marked as executed in the database

  Scenario: Running an executor marks it as executed
    Given the two_executors module is available in planners
    And the attack1 module is available in attacks
    And a plan exists in the database
    And 1 executors for attack1 exists in the database related to the plan
    When the scheduler executes it
    Then the executor is marked as executed in the database
