# Automatically generated by Honest Code
# Do not edit this file as it will be overwritten

Feature: Planners API

  Scenario: Get planners is HAL compilance
    Given there are 2 planners available
    When the user makes a "GET" request to "/planners/" endpoint
    Then the response is HAL
    And the api responds with 2 planners
